// This file is generated by the rs-update-tests script

#include "rs-unit-test.hpp"

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

    // dice-test.cpp
    UNIT_TEST(rs_game_dice_arithmetic)
    UNIT_TEST(rs_game_dice_statistics)
    UNIT_TEST(rs_game_dice_parser)
    UNIT_TEST(rs_game_dice_generation)
    UNIT_TEST(rs_game_dice_literals)

    // english-test.cpp
    UNIT_TEST(rs_game_english_case_conversion)
    UNIT_TEST(rs_game_english_list_formatting)
    UNIT_TEST(rs_game_english_number_formatting)
    UNIT_TEST(rs_game_english_pluralization)
    UNIT_TEST(rs_game_english_lorem_ipsum)

    // hexmap-geometry-test.cpp
    UNIT_TEST(rs_game_hexmap_coordinate_operations)
    UNIT_TEST(rs_game_hexmap_adjacency_properties)

    // hexmap-art-test.cpp
    UNIT_TEST(rs_game_hexmap_ascii_art)
    UNIT_TEST(rs_game_hexmap_xterm_art)

    // version-test.cpp
    UNIT_TEST(rs_game_version)

    // unit-test.cpp

    return RS::UnitTest::end_tests();

}
